name: Release CI
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Cache node modules
        uses: c-hive/gha-{{ MANAGER }}-cache@v1
      - name: Install dependencies
        run: {{#if (isYARN MANAGER)}}yarn install{{else}}npm ci{{/if}}
      - name: Run lint command
        run: {{#if (isYARN MANAGER)}}yarn lint{{else}}npm run lint{{/if}}
  release:
    needs: [lint]
    name: Build and release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: {{#if (isYARN MANAGER)}}yarn install{{else}}npm ci{{/if}}
      - name: Build TypeScript
        run: {{#if (isYARN MANAGER)}}yarn build{{else}}npm run build{{/if}}
      - name: Release
        run: {{#if (isYARN MANAGER)}}yarn release{{else}}npm run release{{/if}}
        env:
          GITHUB_TOKEN: $\{{ secrets.GH_PAT }}
          NPM_TOKEN: $\{{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: "kaaaxcreatorsBOT"
          GIT_AUTHOR_EMAIL: "bernd@kaaaxcreators.de"
          GIT_COMMITTER_NAME: "kaaaxcreatorsBOT"
          GIT_COMMITTER_EMAIL: "bernd@kaaaxcreators.de"